implement capability to write metadata and nos data to S3 bucket
USGS-R/drb-estuary-salinity-ml pull request #20
Opened 2021-12-10 19:30 UTC by ted80810

2021-12-10 21:20 UTC, galengorski approved these changes
This looks good to me, I'll defer to @amsnyder for the s3 syntax though

2021-12-14 18:09 UTC, amsnyder requested changes
Looks good, but I made a few updates. There are two other changes you need to make to make this code run:
- your fetch data function name was changed, so the name needs to be updated when you execute it in main()
- add the new function inputs (s3_bucket and write_location) as inputs to your fetch function in main() where they are executed

It's always a good idea to actually try running the code to make sure it runs before submitting the pull request because I know I am not necessarily testing out the code to see that it works on my local computer!

2021-12-14 18:09 UTC, amsnyder commented on 01_fetch/src/fetch_noaa_nos.py
> +def fetch_metadata(station_id, metadata_outfile, bucket, write_file):
```suggestion
def fetch_metadata(station_id, metadata_outfile, bucket, write_location):
```

2021-12-14 18:09 UTC, amsnyder commented on 01_fetch/src/fetch_noaa_nos.py
> +def fetch_noaa_nos_data(start_dt, end_dt, datum, station_id, time_zone, product, units, file_format, data_outfile, bucket, write_file):
```suggestion
def fetch_noaa_nos_data(start_dt, end_dt, datum, station_id, time_zone, product, units, file_format, data_outfile, bucket, write_location):
```

2021-12-14 18:09 UTC, amsnyder commented on 01_fetch/src/fetch_noaa_nos.py
> +    '''set AWS bucket to read/write to'''
- we want write location to be local by default...we can change it to S3 when we are actually ready to upload
-  moving comments above the line of code they are describing
- set up s3 client for upload

```suggestion
    '''choose where you want to write your data outputs: local or S3'''
    write_location: 'local'
    '''set name of AWS profile storing credentials for S3'''
    aws_profile: 'dev'
    '''set AWS bucket to read/write to'''
    s3_bucket: 'drb-estuary-salinity'
    '''set up AWS client'''
    s3_client = utils.prep_write_location(write_location, aws_profile)
```

2021-12-17 02:16 UTC, merged