add usgs gap analysis
USGS-R/drb-estuary-salinity-ml pull request #38
Opened 2022-01-13 22:27 UTC by amsnyder

Code to produce gap analysis plots for USGS NWIS data. This should be able to run on NOAA data produced by the munge step with just a few additions to the config.

2022-01-14 16:58 UTC, amsnyder commented
I'm just going to merge this so I can make some more updates--it won't impact any of the scripts you are currently working with.  Let me know if you want to make changes though, and I can make any needed updates!

2022-01-14 17:12 UTC, galengorski requested changes
This is looking good, I think these will be really helpful. I got it running on my machine after manually altering one of the munged csv files (see #39). I added some line comments to this PR, other than that, I had a few overall comments:

- Can you make a subdirectory within `data_exploration/out` where the gap analysis plots live? That way they are separate from the gap analysis csvs and a little cleaner to look through.

- I'm looking at the discharge gap plots and the way it is plotted now, it looks like there is missing data in the latest year. Looking at the gap_analysis.csv file, it looks like there is no data for 2021? Is this right or are we just not querying data for 2021?

- I'm looking at the file `usgs_nwis_discharge_01463500_gap_analysis.csv` and I notice a couple of things. For years 2018 and 2020 for example, the p_coverage is 0.939726 but the n_gaps for both years is 0, also for 2012 p_coverage = 1 and n_gap = 1 as well. Seems like maybe the gaps aren't being calculated or logged correctly?

2022-01-14 17:14 UTC, amsnyder commented on utils.py
> +
Thanks for catching that!

2022-01-14 17:15 UTC, amsnyder commented on data_exploration/src/gap_analysis.py
> +os.makdirs('data_exploration/out/', exist_ok  = True)
```suggestion
    os.makdirs('data_exploration/out/', exist_ok  = True)
```

2022-01-14 17:23 UTC, amsnyder commented on data_exploration/src/gap_analysis.py
> +    return metric_dfs
```suggestion
    return metric_dfs, metrics
```

2022-01-14 17:23 UTC, amsnyder commented on data_exploration/src/gap_analysis.py
> +    metric_dfs = gap_analysis_calc(source, var_dfs)
```suggestion
    metric_dfs, metrics = gap_analysis_calc(source, var_dfs)
```

2022-01-14 17:23 UTC, amsnyder commented on data_exploration/src/gap_analysis.py
> +    plot_gap_analysis(source, metric_dfs, site_colors)
```suggestion
    plot_gap_analysis(source, metric_dfs, metrics, site_colors)
```

2022-01-14 17:23 UTC, amsnyder commented on data_exploration/src/gap_analysis.py
> +def plot_gap_analysis(source, metric_dfs, site_colors):
```suggestion
def plot_gap_analysis(source, metric_dfs, metrics, site_colors):
```

2022-01-18 15:14 UTC, amsnyder commented
For the first bullet point, I added one directory for plots and one for csvs. Let me know if that looks ok.

2022-01-19 18:42 UTC, amsnyder commented
For the third bullet point, I was losing gaps at the start and end of the year, and I've updated the code so those are not missed.

2022-01-19 18:43 UTC, amsnyder commented
@galengorski - I think I've addressed your concerns, but please let me know if I've missed anything! Otherwise, I think I will merge this request.

2022-01-19 20:55 UTC, galengorski commented
Thanks @amsnyder, this sound good to me, I'm not going to run it on my machine, but since it isn't connected to any other part of the pipeline we can merge it now and always revisit if we want to make changes.

2022-01-19 20:57 UTC, merged